// districtData.js
// coverQuery   → used by Districts.jsx to fetch one card photo via Unsplash API
// galleryQueries → used by DistrictPage.jsx to fetch ~10 gallery photos

export const districts = [
  {
    slug: "anuradhapura", name: "Anuradhapura", province: "North Central",
    tagline: "Ancient Kingdom, Modern Crisis",
    description: "Anuradhapura is Sri Lanka's most historically significant district and the highest human-elephant conflict hotspot in the country. Home to the sacred Sri Maha Bodhi tree and ancient stupas, its dry zone forests are the primary habitat of Sri Lanka's wild elephant population. In 2022 alone, 90 elephants and 37 humans lost their lives here.",
    wildlife: ["Asian Elephant", "Leopard", "Sloth Bear", "Sambar Deer", "Wild Boar", "Crocodile"],
    nationalParks: ["Wilpattu National Park", "Kaudulla National Park", "Minneriya National Park"],
    conflictLevel: "Critical", elephantsLost: 90, humansLost: 37, area: "7,179 km²", population: "856,231",
    coverQuery: "anuradhapura ancient ruins sri lanka",
    galleryQueries: ["anuradhapura stupa sri lanka", "wilpattu national park leopard", "sri lanka wild elephant forest", "minneriya elephant gathering", "anuradhapura ancient kingdom"],
  },
  {
    slug: "polonnaruwa", name: "Polonnaruwa", province: "North Central",
    tagline: "Medieval Ruins, Living Wilderness",
    description: "Polonnaruwa, home to the ancient medieval kingdom, is the second most affected district by human-elephant conflict. The Minneriya and Kaudulla national parks host the largest elephant gatherings in Asia — the famous 'Elephant Gathering' draws hundreds of elephants each dry season.",
    wildlife: ["Asian Elephant", "Toque Macaque", "Mugger Crocodile", "Sambar Deer", "Spotted Deer", "Painted Stork"],
    nationalParks: ["Minneriya National Park", "Kaudulla National Park", "Hurulu Eco Park"],
    conflictLevel: "Critical", elephantsLost: 73, humansLost: 19, area: "3,293 km²", population: "406,088",
    coverQuery: "polonnaruwa ancient temple sri lanka",
    galleryQueries: ["polonnaruwa ruins sri lanka", "minneriya elephant gathering sri lanka", "kaudulla national park elephant", "sri lanka ancient temple", "elephant herd sri lanka lake"],
  },
  {
    slug: "ampara", name: "Ampara", province: "Eastern",
    tagline: "Eastern Shores, Ancient Forests",
    description: "Ampara district on Sri Lanka's eastern coast is a biodiversity hotspot where tropical forests meet the Indian Ocean. It ranks among the top three districts for human-elephant conflict, with particularly high property damage from elephant raids on paddy fields.",
    wildlife: ["Asian Elephant", "Sri Lanka Leopard", "Sloth Bear", "Wild Buffalo", "Mugger Crocodile", "Saltwater Crocodile"],
    nationalParks: ["Lahugala Kitulana National Park", "Gal Oya National Park"],
    conflictLevel: "High", elephantsLost: 45, humansLost: 15, area: "4,415 km²", population: "649,402",
    coverQuery: "arugam bay sri lanka beach",
    galleryQueries: ["arugam bay sri lanka", "gal oya national park elephant", "sri lanka eastern coast", "ampara paddy field sri lanka", "sri lanka elephant river"],
  },
  {
    slug: "kurunegala", name: "Kurunegala", province: "North Western",
    tagline: "Rock Fortresses and Rubber Estates",
    description: "Kurunegala, named after the iconic Elephant Rock fortress, is one of Sri Lanka's most populous districts and a major HEC hotspot. The northern parts border elephant corridors connecting Wilpattu and other protected areas.",
    wildlife: ["Asian Elephant", "Sloth Bear", "Leopard", "Purple-faced Leaf Monkey", "Wild Boar", "Monitor Lizard"],
    nationalParks: ["Wilpattu National Park (border)", "Kahalla-Pallekele Elephant Corridor"],
    conflictLevel: "High", elephantsLost: 30, humansLost: 12, area: "4,812 km²", population: "1,618,465",
    coverQuery: "kurunegala rock fortress sri lanka",
    galleryQueries: ["kurunegala sri lanka", "wilpattu national park wildlife", "sri lanka rubber estate plantation", "elephant corridor sri lanka forest", "sri lanka leopard wild"],
  },
  {
    slug: "hambantota", name: "Hambantota", province: "Southern",
    tagline: "Southern Wilderness and Whale Watching",
    description: "Hambantota in the deep south is home to Yala National Park — the most visited national park in Sri Lanka and one of the world's best leopard-spotting destinations. Infrastructure developments have fragmented critical elephant corridors.",
    wildlife: ["Sri Lanka Leopard", "Asian Elephant", "Sloth Bear", "Mugger Crocodile", "Blue Whale", "Sperm Whale"],
    nationalParks: ["Yala National Park", "Bundala National Park", "Lunugamvehera National Park"],
    conflictLevel: "Moderate", elephantsLost: 20, humansLost: 8, area: "2,609 km²", population: "599,903",
    coverQuery: "yala national park leopard sri lanka",
    galleryQueries: ["yala national park leopard", "bundala national park flamingo sri lanka", "sri lanka whale watching", "hambantota wildlife sri lanka", "yala elephant crocodile"],
  },
  {
    slug: "kandy", name: "Kandy", province: "Central",
    tagline: "Cultural Capital, Cloud Forest",
    description: "Kandy, Sri Lanka's cultural capital and home to the sacred Temple of the Tooth Relic, sits at the heart of the island's central highlands. The surrounding forests are a UNESCO World Heritage site.",
    wildlife: ["Sri Lanka Leopard", "Purple-faced Leaf Monkey", "Toque Macaque", "Asian Elephant", "Sambar Deer", "Sri Lanka Junglefowl"],
    nationalParks: ["Knuckles Mountain Range (UNESCO)", "Victoria-Randenigala Reservoir"],
    conflictLevel: "Moderate", elephantsLost: 10, humansLost: 5, area: "1,940 km²", population: "1,375,382",
    coverQuery: "kandy temple tooth relic sri lanka",
    galleryQueries: ["kandy lake sri lanka", "temple of tooth kandy", "knuckles mountain range sri lanka", "kandy perahera elephant", "sri lanka cloud forest"],
  },
  {
    slug: "ratnapura", name: "Ratnapura", province: "Sabaragamuwa",
    tagline: "City of Gems, Peak Wilderness",
    description: "Ratnapura, the 'City of Gems', is famous for its precious stones and Sinharaja — Sri Lanka's last remaining tropical rainforest and UNESCO World Heritage site. This district is a treasure trove of endemic species found nowhere else on Earth.",
    wildlife: ["Sri Lanka Leopard", "Purple-faced Leaf Monkey", "Red Slender Loris", "Sri Lanka Green Pigeon", "Green Pit Viper", "Asian Elephant"],
    nationalParks: ["Sinharaja Forest Reserve (UNESCO)", "Udawalawa National Park (border)"],
    conflictLevel: "Low", elephantsLost: 5, humansLost: 3, area: "3,275 km²", population: "1,082,757",
    coverQuery: "sinharaja rainforest sri lanka",
    galleryQueries: ["sinharaja forest reserve sri lanka", "sri lanka rainforest endemic birds", "ratnapura gem mining", "sri lanka tropical forest canopy", "sinharaja wildlife sri lanka"],
  },
  {
    slug: "monaragala", name: "Monaragala", province: "Uva",
    tagline: "Uva Wilderness, Peacock Mountains",
    description: "Monaragala (Peacock Rock) in Uva province is one of Sri Lanka's least developed but most biodiverse districts. Its vast dry forests and proximity to Yala make it a critical elephant corridor.",
    wildlife: ["Asian Elephant", "Sri Lanka Leopard", "Sloth Bear", "Indian Peafowl", "Mugger Crocodile", "Python"],
    nationalParks: ["Yala National Park (Block 2)", "Lunugamvehera National Park"],
    conflictLevel: "High", elephantsLost: 28, humansLost: 10, area: "5,639 km²", population: "451,058",
    coverQuery: "monaragala dry forest sri lanka",
    galleryQueries: ["monaragala sri lanka wilderness", "yala block 2 elephant", "sri lanka peacock indian peafowl", "uva province sri lanka landscape", "sri lanka sloth bear wild"],
  },
  {
    slug: "trincomalee", name: "Trincomalee", province: "Eastern",
    tagline: "Natural Harbour, Whale Watching Capital",
    description: "Trincomalee boasts one of the world's finest natural harbours and is Sri Lanka's premier whale and dolphin watching destination. Somawathiya National Park is a critical elephant habitat.",
    wildlife: ["Blue Whale", "Sperm Whale", "Spinner Dolphin", "Asian Elephant", "Mugger Crocodile", "Green Sea Turtle"],
    nationalParks: ["Somawathiya National Park", "Pigeon Island National Park"],
    conflictLevel: "Moderate", elephantsLost: 15, humansLost: 7, area: "2,727 km²", population: "379,541",
    coverQuery: "trincomalee harbour beach sri lanka",
    galleryQueries: ["trincomalee bay sri lanka", "pigeon island coral reef sri lanka", "sri lanka blue whale ocean", "somawathiya national park elephant", "trincomalee beach coast"],
  },
  {
    slug: "matale", name: "Matale", province: "Central",
    tagline: "Spice Gardens and Ancient Temples",
    description: "Matale sits within the Kahalla-Pallekele elephant corridor and is surrounded by ancient temples, cinnamon gardens and the dramatic Knuckles Mountain Range.",
    wildlife: ["Asian Elephant", "Leopard", "Sloth Bear", "Sambar Deer", "Purple-faced Leaf Monkey", "Sri Lanka Junglefowl"],
    nationalParks: ["Knuckles Mountain Range", "Kahalla-Pallekele Elephant Corridor"],
    conflictLevel: "Moderate", elephantsLost: 18, humansLost: 7, area: "1,993 km²", population: "484,531",
    coverQuery: "dambulla cave temple sri lanka",
    galleryQueries: ["dambulla cave temple sri lanka", "matale spice garden sri lanka", "sigiriya rock fortress sri lanka", "knuckles mountain sri lanka", "sri lanka elephant corridor"],
  },
  {
    slug: "puttalam", name: "Puttalam", province: "North Western",
    tagline: "Lagoons, Salt Flats and Mangroves",
    description: "Puttalam borders Wilpattu National Park — Sri Lanka's largest national park — making it a major elephant corridor. Flamingos, dugongs and crocodiles thrive in the lagoon system.",
    wildlife: ["Asian Elephant", "Fishing Cat", "Mugger Crocodile", "Painted Stork", "Flamingo", "Dugong"],
    nationalParks: ["Wilpattu National Park", "Puttalam Lagoon"],
    conflictLevel: "High", elephantsLost: 25, humansLost: 9, area: "3,072 km²", population: "762,396",
    coverQuery: "puttalam lagoon mangrove sri lanka",
    galleryQueries: ["puttalam lagoon sri lanka", "wilpattu national park wildlife", "sri lanka flamingo lagoon", "fishing cat sri lanka wetland", "sri lanka mangrove forest"],
  },
  {
    slug: "badulla", name: "Badulla", province: "Uva",
    tagline: "Tea Country and Cloud Forests",
    description: "Badulla in the Uva highlands is Sri Lanka's tea country — rolling hills covered in emerald green tea estates with breathtaking waterfalls. The district has the highest property damage from elephant conflict.",
    wildlife: ["Sri Lanka Leopard", "Sambar Deer", "Asian Elephant", "Purple-faced Leaf Monkey", "Sri Lanka Whistling Thrush", "Sloth Bear"],
    nationalParks: ["Horton Plains National Park", "Dunhinda Falls"],
    conflictLevel: "High", elephantsLost: 22, humansLost: 8, area: "2,861 km²", population: "812,072",
    coverQuery: "badulla tea plantation uva sri lanka",
    galleryQueries: ["badulla tea estate sri lanka", "horton plains worlds end sri lanka", "dunhinda falls sri lanka", "uva highlands sri lanka", "sri lanka sambar deer forest"],
  },
  {
    slug: "galle", name: "Galle", province: "Southern",
    tagline: "Colonial Fort, Coral Reefs",
    description: "Galle, home to the iconic Dutch colonial fort and world-class surf breaks, is Sri Lanka's most visited tourist destination in the south. The Hikkaduwa coral reef is one of the most biodiverse marine ecosystems in the Indian Ocean.",
    wildlife: ["Green Sea Turtle", "Spinner Dolphin", "Sri Lanka Leopard", "Purple-faced Leaf Monkey", "Flying Fox", "Monitor Lizard"],
    nationalParks: ["Hikkaduwa National Park", "Kanneliya Forest Reserve"],
    conflictLevel: "Low", elephantsLost: 3, humansLost: 1, area: "1,652 km²", population: "1,063,135",
    coverQuery: "galle fort sri lanka aerial",
    galleryQueries: ["galle fort dutch colonial sri lanka", "hikkaduwa coral reef turtle sri lanka", "galle lighthouse coast", "sri lanka sea turtle ocean", "galle beach surfing"],
  },
  {
    slug: "matara", name: "Matara", province: "Southern",
    tagline: "Southern Coast, Whale Watching",
    description: "Matara at the southernmost tip of Sri Lanka is known for its colonial star fort, beautiful beaches and proximity to whale watching spots.",
    wildlife: ["Blue Whale", "Sperm Whale", "Spinner Dolphin", "Green Sea Turtle", "Sri Lanka Leopard", "Purple-faced Leaf Monkey"],
    nationalParks: ["Sinharaja Forest (border)"],
    conflictLevel: "Low", elephantsLost: 2, humansLost: 1, area: "1,270 km²", population: "814,048",
    coverQuery: "mirissa beach whale watching sri lanka",
    galleryQueries: ["mirissa beach sri lanka", "matara star fort sri lanka", "sri lanka whale watching ocean", "mirissa whale dolphin", "southern coast sri lanka beach"],
  },
  {
    slug: "colombo", name: "Colombo", province: "Western",
    tagline: "The Commercial Capital",
    description: "Colombo, Sri Lanka's vibrant commercial capital, is a modern city where colonial heritage blends with contemporary architecture. The Colombo wetlands are a critically important bird sanctuary.",
    wildlife: ["Purple Heron", "Little Cormorant", "Painted Stork", "Mugger Crocodile", "Flying Fox", "Monitor Lizard"],
    nationalParks: ["Colombo Wetlands", "Bellanwila-Attidiya Sanctuary"],
    conflictLevel: "Minimal", elephantsLost: 0, humansLost: 0, area: "676 km²", population: "2,324,349",
    coverQuery: "colombo city skyline sri lanka",
    galleryQueries: ["colombo skyline lotus tower", "colombo city sri lanka", "gangaramaya temple colombo", "colombo wetlands birds", "colombo port city"],
  },
  {
    slug: "gampaha", name: "Gampaha", province: "Western",
    tagline: "Gateway to the North",
    description: "Gampaha, the most populous district outside Colombo, contains Muthurajawela marsh — one of Sri Lanka's most important coastal wetlands and a birding hotspot with over 190 bird species.",
    wildlife: ["Fishing Cat", "Purple Heron", "Mugger Crocodile", "Monitor Lizard", "Flying Fox", "Sri Lanka Leopard"],
    nationalParks: ["Muthurajawela Wetlands"],
    conflictLevel: "Minimal", elephantsLost: 1, humansLost: 0, area: "1,387 km²", population: "2,304,833",
    coverQuery: "muthurajawela wetlands sri lanka",
    galleryQueries: ["muthurajawela marsh wetland sri lanka", "gampaha sri lanka", "negombo lagoon birds", "sri lanka fishing cat wetland", "western province sri lanka nature"],
  },
  {
    slug: "kalutara", name: "Kalutara", province: "Western",
    tagline: "Coconut Palms and River Estuaries",
    description: "Kalutara is a coastal district famous for its golden beaches, coconut plantations and the iconic Kalutara Bodhiya. The Kalu Ganga river supports rich freshwater biodiversity.",
    wildlife: ["Fishing Cat", "Purple-faced Leaf Monkey", "River Otter", "Sri Lanka Green Pigeon", "Monitor Lizard", "Flying Fox"],
    nationalParks: ["Sinharaja Forest (border)", "Kalu Ganga Estuary"],
    conflictLevel: "Low", elephantsLost: 2, humansLost: 1, area: "1,598 km²", population: "1,221,948",
    coverQuery: "kalutara beach coconut sri lanka",
    galleryQueries: ["kalutara beach sri lanka", "kalu river estuary sri lanka", "sri lanka coconut palm coast", "kalutara bodhiya temple", "sri lanka river otter"],
  },
  {
    slug: "nuwara-eliya", name: "Nuwara Eliya", province: "Central",
    tagline: "Little England, Tea Highlands",
    description: "Nuwara Eliya, nicknamed 'Little England', sits at 1,868m above sea level. Famous for its cool climate, strawberry farms, colonial bungalows and world-renowned tea estates.",
    wildlife: ["Sri Lanka Leopard", "Sambar Deer", "Purple-faced Leaf Monkey", "Sri Lanka Whistling Thrush", "Dull-blue Flycatcher", "Sloth Bear"],
    nationalParks: ["Horton Plains National Park", "Victoria Park"],
    conflictLevel: "Low", elephantsLost: 3, humansLost: 1, area: "1,741 km²", population: "706,011",
    coverQuery: "nuwara eliya tea plantation highlands sri lanka",
    galleryQueries: ["nuwara eliya little england sri lanka", "horton plains national park", "nuwara eliya tea estate colonial", "worlds end horton plains", "sri lanka highland fog forest"],
  },
  {
    slug: "kegalle", name: "Kegalle", province: "Sabaragamuwa",
    tagline: "Pinnawala Elephants, Rubber Estates",
    description: "Kegalle is home to the world-famous Pinnawala Elephant Orphanage, where orphaned and injured elephants are cared for. This district represents both the challenge and compassion of Sri Lanka's conservation story.",
    wildlife: ["Asian Elephant", "Sri Lanka Leopard", "Purple-faced Leaf Monkey", "Sloth Bear", "Sambar Deer", "Monitor Lizard"],
    nationalParks: ["Pinnawala Elephant Orphanage", "Kithulgala Forest Reserve"],
    conflictLevel: "Moderate", elephantsLost: 12, humansLost: 4, area: "1,693 km²", population: "840,648",
    coverQuery: "pinnawala elephant orphanage sri lanka",
    galleryQueries: ["pinnawala elephant orphanage baby", "kegalle rubber estate sri lanka", "sri lanka elephant bathing river", "kithulgala white water rafting", "pinnawala elephant herd"],
  },
  {
    slug: "jaffna", name: "Jaffna", province: "Northern",
    tagline: "Peninsula of Temples and Lagoons",
    description: "Jaffna, the cultural capital of Sri Lanka's north, is a peninsula of ancient Hindu temples, vast lagoons and unique Tamil heritage. Flamingos, dugongs and sea turtles thrive in undisturbed waters.",
    wildlife: ["Flamingo", "Painted Stork", "Dugong", "Green Sea Turtle", "Fishing Cat", "Monitor Lizard"],
    nationalParks: ["Delft Island", "Casuarina Beach"],
    conflictLevel: "Minimal", elephantsLost: 0, humansLost: 0, area: "1,025 km²", population: "599,856",
    coverQuery: "jaffna hindu temple lagoon sri lanka",
    galleryQueries: ["jaffna peninsula sri lanka", "jaffna fort historic", "nainativu temple jaffna", "jaffna lagoon flamingo", "sri lanka northern province coast"],
  },
  {
    slug: "mannar", name: "Mannar", province: "Northern",
    tagline: "Adam's Bridge, Flamingo Sanctuary",
    description: "Mannar island is famous for Adam's Bridge (Ram Setu) and the largest flamingo colonies in South Asia. Wilpattu National Park borders the district, with elephants frequently crossing into farming areas.",
    wildlife: ["Greater Flamingo", "Painted Stork", "Asian Elephant", "Dugong", "Fishing Cat", "Spoonbill"],
    nationalParks: ["Wilpattu National Park (border)", "Giant's Tank"],
    conflictLevel: "Moderate", elephantsLost: 8, humansLost: 3, area: "1,996 km²", population: "99,051",
    coverQuery: "mannar island sri lanka flamingo",
    galleryQueries: ["mannar island sri lanka", "adams bridge sri lanka", "giant tank mannar birds", "sri lanka flamingo flock", "mannar baobab tree sri lanka"],
  },
  {
    slug: "vavuniya", name: "Vavuniya", province: "Northern",
    tagline: "Northern Gateway, Forest Frontier",
    description: "Vavuniya is the gateway to Sri Lanka's north and a district of vast dry forests, located on the elephant corridor between Wilpattu and Yala.",
    wildlife: ["Asian Elephant", "Sloth Bear", "Sambar Deer", "Mugger Crocodile", "Indian Peafowl", "Painted Stork"],
    nationalParks: ["Madhu Road Sanctuary", "Giant's Tank"],
    conflictLevel: "Moderate", elephantsLost: 12, humansLost: 5, area: "1,967 km²", population: "172,115",
    coverQuery: "vavuniya dry forest elephant sri lanka",
    galleryQueries: ["vavuniya sri lanka north", "sri lanka dry zone forest", "elephant corridor northern sri lanka", "madhu church sri lanka", "sri lanka wild elephant road"],
  },
  {
    slug: "mullaitivu", name: "Mullaitivu", province: "Northern",
    tagline: "Remote Coast, Recovering Wilderness",
    description: "Mullaitivu, on Sri Lanka's northeast coast, is in a phase of remarkable ecological recovery. Wildlife is returning rapidly to undisturbed coastal forests.",
    wildlife: ["Asian Elephant", "Sloth Bear", "Green Sea Turtle", "Dugong", "Mugger Crocodile", "Painted Stork"],
    nationalParks: ["Nanthikadal Lagoon"],
    conflictLevel: "Moderate", elephantsLost: 10, humansLost: 4, area: "2,617 km²", population: "92,228",
    coverQuery: "mullaitivu coast lagoon sri lanka",
    galleryQueries: ["mullaitivu coast sri lanka", "nanthikadal lagoon sri lanka", "sri lanka northeast beach", "sea turtle nesting beach sri lanka", "sri lanka coastal forest recovery"],
  },
  {
    slug: "kilinochchi", name: "Kilinochchi", province: "Northern",
    tagline: "Resilient North, Emerging Wilderness",
    description: "Kilinochchi is a district of remarkable recovery and rebuilding. Its dry forests are part of the northern elephant corridor, with farming communities in close contact with wildlife.",
    wildlife: ["Asian Elephant", "Sambar Deer", "Indian Peafowl", "Painted Stork", "Mugger Crocodile", "Monitor Lizard"],
    nationalParks: ["Iranamadu Tank"],
    conflictLevel: "Moderate", elephantsLost: 8, humansLost: 3, area: "1,279 km²", population: "113,510",
    coverQuery: "kilinochchi northern sri lanka landscape",
    galleryQueries: ["kilinochchi sri lanka", "iranamadu tank birds", "sri lanka northern dry zone", "indian peafowl peacock sri lanka", "sri lanka elephant paddy field"],
  },
  {
    slug: "batticaloa", name: "Batticaloa", province: "Eastern",
    tagline: "Singing Fish and Lagoon Life",
    description: "Batticaloa, famous for its mysterious 'singing fish' phenomenon, is a district of stunning coastal beauty. The vast Batticaloa Lagoon is one of Sri Lanka's most important waterbird habitats.",
    wildlife: ["Green Sea Turtle", "Spinner Dolphin", "Asian Elephant", "Painted Stork", "Mugger Crocodile", "Fishing Cat"],
    nationalParks: ["Batticaloa Lagoon"],
    conflictLevel: "Moderate", elephantsLost: 14, humansLost: 6, area: "2,854 km²", population: "526,567",
    coverQuery: "batticaloa lagoon beach sri lanka",
    galleryQueries: ["batticaloa lagoon sri lanka", "batticaloa beach east coast", "sri lanka painted stork lagoon", "eastern province coast sri lanka", "sri lanka fishing village lagoon"],
  },
]

export const conflictColors = {
  Critical: { bg: "bg-red-500/20",     text: "text-red-400",     border: "border-red-500/30" },
  High:     { bg: "bg-orange-500/20",  text: "text-orange-400",  border: "border-orange-500/30" },
  Moderate: { bg: "bg-yellow-500/20",  text: "text-yellow-400",  border: "border-yellow-500/30" },
  Low:      { bg: "bg-emerald-500/20", text: "text-emerald-400", border: "border-emerald-500/30" },
  Minimal:  { bg: "bg-stone-500/20",   text: "text-stone-400",   border: "border-stone-500/30" },
}
